# Generated by Django 4.1.4 on 2023-04-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='problem_type',
            field=models.CharField(default='unproblematic', max_length=50),
        ),
    ]
