# Generated by Django 4.1.4 on 2023-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_alter_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='media',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='source',
            field=models.CharField(max_length=200),
        ),
    ]
