# Generated by Django 4.1.4 on 2023-06-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_alter_tweet_media_alter_tweet_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
